language: python
python:
  - "3.6"

addons:
  sonarcloud:
    organization: git-confused-team3 # the key of the org you chose at step #3
    token:
      secure: G38mI0fOknzStb0Fqq1If75OIpKgjkuCQq0fm2TiM3uhzowaoBLzLwTubC+CQTX1emCzXftRRsx9dJccFfXBfLxk6EM8yzLVP2eCnUflSKwVMGcEAiU6XEuccOtXm1TsQsvi1+FuGGWwUxBZNBR/IqZkSg3AEC5EMwYL4UdM6Pkzmf+/cehfiOyIjmNJ0St2DhBiyYqz4nhpCy9XCj3U/pG+TyRdw0VgdfquqPKrbRxMfgi+q9nhofqOclZRd8fXeCYn2wfK4fvR6albFoufpFzfkqfcQznWlbGa47wvACidW0jwG8QiW2XGqJG7hDEg7tMek6woZmh7TvgsluPNjfJ8CIhgtTnBAlcagFbmDTzEnEWuWFKvWtu7QOfuSlwZV2gPF1pt2M1yyj1aDd6MswIHlRsHWdoVQlWEhL5hv0z4z6rsUYZGQVyU19t4mr646Ln84HyKB9WvnnIU5NE//SJCZ2hwKBPlVDKVqpKcORPSstlD85l8crdm30NbWdkRV9O2ZBjXcAPV2VjKvdw50Bos+54iwysPffuH6CGma3nuM3VRjyim27h5dAcBxw9NmdzOOBF5AUTHc8LpqzBzsSYyOsK5VOwsIYHRYC+wLIyXc3wh2yYmVX3jvD7W3M+WI80N6pU9l6yAGkqftfaZpg9p3nJahTfhbrzyGZYEbsQ=

install:
  - pip install codecov

script:
  # - coverage run --omit=*test* -m unittest
  - coverage run --omit=*test* -m unittest jvpm
  - sonar-scanner


after_success:
  - codecov
