language: python
python:
  - "3.6"
  
addons:
  sonarcloud:
    organization: zkhalido-github # the key of the org you chose at step #3
    token:
      secure: fqI99cKL/mzLjuq7vn3PET5O1wS9wZ2yqpFlD2fwR5cjfpT7dD2e+AiG+JUESbeluYD7l8hVwp2GaJ3KyA2ruvjC+x2MsqvZmAuln9g+um/kRJnRs2PxfYDjjtwEMxjO3die4kbn5SvfBSi5foPa3mh8CEiQa8kI1WEOH3rv0m8IktmGma+TOQkBz5YNFmS7pdvNNrr5BNK8keR6nRiYuLE4gtCX+eNH3RRYlDw74SiPF9YU6R/7Q3UFOFLO63bn4N8tI9kzXJyjWQhYeAAy9Y2OegjF0YHfywu9lMXxX/l9941N0iv2SxnSxRlckaBxbf0jbZMyIGUnHG7vn64PQ4KZaOw4T1VgJZ9hyCcQMwcDD8N7YNtQLFt1XoczJktA1OXlBa5gm4U867/aS1VRZ78CY2aYAWecJqjX1oynJ7x53VIwZ8i+XHUIXr/D5OCNjwzmx2o70xFsIh4OAKOR2zYB6KQSFtTIBYF9Lj6wFuSuIpChBcsvtHlbIZWxfZyFVc3XWGVRg74ys1wPkw7cTnktfAs7JOmc8AzQgzIDlmihGFbrS9CRrD4DejqU1je4JBCpWX5FJShfvJpONwU9CA4eHg+U3PZDYdA9EkiCrSDYVEnXXexQkqNREmlc76m0s7saU56e0IGZDCU/Y+jPPLtN4JeRL37i3J8FMLtRUGs=

  
  
install:
  - pip install codecov

script:
  - coverage run --omit=*test* -m unittest
  - sonar-scanner


after_success:
  - codecov
