language: python
python:
  - "3.6"

addons:
  sonarcloud:
    organization: git-confused-team3 # the key of the org you chose at step #3
    token: ${newToken}  
    
dist: trusty
language: python
python:
  - "3.6"

install:
  - pip install codecov

script:
  - coverage run -m unittest
  - coverage xml -i
  - sonar-scanner
  

after_success:
  - codecov
