language: python
python:
  - "3.6"

addons:
  sonarcloud:
    organization: git-confused-team3 # the key of the org you chose at step #3
    token:
      secure: "Ijk4AOCyoBte0GLeOVt7qhp0AgqiCSE4xr+GWGIWp0VGq4H9hTDhFtgo6HE7Hyicz6ivbXTdufp+ioyDM/wfs9w63T1a6lSUsfCjB3KeXz8JhjDDDXbPFOJhW6xlnWgAWRwiTAMED6IoUH3rROt1Nj59x59hdDZT3fdYonz9FjNMYYbRF4vTSJyMBbAURP7avX9p+mnrtuk8+b71INdmcUbZ/MDDVbA5UV8yfy0G9Zb3DHbHbVPBF63vqySodP9BTT97nhWBoIRYny/d7nYv+1EOPeaYFzroFztQH+MTYa/gLPDU+Oz/DiL6+in01DYT3GsPNEVd5hsoB5algJot8iNVsJ1p0hlWCkKwWR+ZchhFIXfp9p1oJLAHrdKeucEfsVlcBDDOFUwu7PQsJkEfJyRCgIynQ2ZwtYkyPNKmRqmKSW5Cc4tepfTGt33DGCatJEjSwH598kBt0OoztQjpNQnXqSDRKMdh8yYpxcecwefiEVKvcSVogI2flcfaliZac18Lc+ZlvcAxSy17RAQe7cndocjBmU+J5EG1Wvsla1hgkRLOmBLgmLaGMmhZsmdtMj9YDE6iGiJeDS5XMXKTjnqPxvJ7qVXHTa0806HM2TgMO/abUBR4iiB9v2RpcX2vp76L56/4PJbdIKoQPMEPX7xJ653gmzqguKSRxDHyCYk="

install:
  - pip install codecov

script:
  # - coverage run --omit=*test* -m unittest
  - coverage run --omit=*test* -m unittest jvpm.py
  - sonar-scanner


after_success:
  - codecov
