language: python
python:
  - "3.6"

install:
  - pip install codecov

script:
  - coverage run --omit=*test* -m unittest

after_success:
  - codecov

addons:
  sonarcloud:
    organization: zkhalido-github # the key of the org you chose at step #3
    token: 85dfbefeef551eeb398b0d4e9b0b4b6c97465a5e
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
