language: python
python:
  - "3.6"

addons:
  sonarcloud:
    organization: git-confused-team3 # the key of the org you chose at step #3
    token:
      secure: 



install:
  - pip install codecov

script:
  # - coverage run --omit=*test* -m unittest
  - coverage run --omit=*test* -m unittest jvpm.py
  - sonar-scanner


after_success:
  - codecov
