language: python
python:
  - "3.6"
  #- "3.5"

#addons:
  #sonarcloud:
   # organization: git-confused-team3 # the key of the org you chose at step #3
   # token: ${newToken}  
    
dist: trusty

install:
  - pip install codecov
  - pip install numpy
  - pip install coverage

script:
  - coverage run -m unittest
  - coverage xml -i
  - sonar-scanner
after_success:
  - codecov

  
addons:
 sonarcloud:
   organization: git-confused-team3 # the key of the org you chose at step #3
   token: 
     secure: ${newToken}  
    
