language: python
python:
  - "3.6"

addons:
  sonarcloud:
    organization: git-confused-team3
    #git-confused-team3 # the key of the org you chose at step #3
    token:182ff312ceb2059a76227db27712020ab22741c0 
    #${SONAR_TOKEN}
    
dist: trusty
language: python
python:
  - "3.6"

install:
  - pip install codecov

script:
  - coverage run -m unittest
  - coverage xml -i
  - sonar-scanner

after_success:
  - codecov
